import { NextResponse } from "next/server";

/* Dynamic Firebase Cloud Messaging service worker.
   Served at /firebase-messaging-sw.js with the public Firebase config injected
   from env vars (so we never hard-code keys in a checked-in file).

   FCM requires the SW to live at the root of the origin and be reachable at
   exactly this path — a Next.js route handler is the cleanest way to do that
   while still using NEXT_PUBLIC_* env vars. */
export async function GET() {
  const cfg = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  const body = `/* eslint-disable no-undef */
// Auto-generated by /src/app/firebase-messaging-sw.js/route.ts — do not edit.

importScripts("https://www.gstatic.com/firebasejs/12.13.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/12.13.0/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(cfg)});

const messaging = firebase.messaging();

// Background push → show an OS notification. The 'data' payload carries the
// deep-link URL we want to open on tap.
messaging.onBackgroundMessage((payload) => {
  const title = (payload.notification && payload.notification.title) || "BlaBlue";
  const body = (payload.notification && payload.notification.body) || "";
  const url = (payload.data && payload.data.url) || "/";
  const tag = (payload.data && payload.data.tag) || undefined;
  self.registration.showNotification(title, {
    body,
    icon: "/icons/icon-192.png",
    badge: "/icons/icon-192.png",
    data: { url },
    tag,
  });
});

// Tap a notification → focus an existing BlaBlue tab on the right page,
// or open a new one.
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || "/";
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((clients) => {
      for (const c of clients) {
        if ("focus" in c) {
          c.navigate(url);
          return c.focus();
        }
      }
      return self.clients.openWindow(url);
    })
  );
});
`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Service-Worker-Allowed": "/",
      "Cache-Control": "public, max-age=0, must-revalidate",
    },
  });
}
